# Generated by Django 5.2.4 on 2025-07-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma-separated tech tags', max_length=300)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('coming_soon', 'Coming Soon')], default='live', max_length=20)),
            ],
        ),
    ]
