# Generated by Django 5.2.4 on 2025-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_skill_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated tech tags', max_length=300),
        ),
    ]
