# Generated by Django 5.2.4 on 2025-08-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated tech tags (e.g. Django, JavaScript, CSS)', max_length=300),
        ),
    ]
