# Generated by Django 5.2.4 on 2025-08-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_project_youtube_link_alter_project_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(default='https://allnvysbhq.cloudimg.io/v7/www.projectsmart.co.uk/img/project.png', help_text='Paste the URL of the project image (e.g. hosted on Imgur, Cloudinary, etc.)', max_length=500),
            preserve_default=False,
        ),
    ]
